kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
  - containerPort: 30080
    hostPort: 9180
    protocol: TCP
  - containerPort: 30562
    hostPort: 9562
    protocol: TCP
  - containerPort: 30090
    hostPort: 9190
    protocol: TCP
  - containerPort: 30100
    hostPort: 9100
    protocol: TCP
- role: worker
- role: worker
- role: worker
- role: worker
